#!/bin/bash

PID_FILE="/var/run/my_process.pid"
SCRIPT_PATH="$(dirname "$(realpath "$0")")/manage_my_process"

start() {
    echo "Checking if process is already running..."
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running."
        return
    fi
    
    echo "Starting manage_my_process..."
    $SCRIPT_PATH &
    echo $! > "$PID_FILE"
    echo "manage_my_process started with PID $(cat $PID_FILE)"
}

stop() {
    if [ -f "$PID_FILE" ]; then
        kill $(cat "$PID_FILE")
        rm "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
